import { useEffect, useState, type ReactNode } from "react";
import { Bell, Database, Globe2, Palette, RotateCcw, Save, ShieldCheck } from "lucide-react";

interface PlatformSettings { defaultRegion: string; refreshInterval: string; emissionsFactor: string; temperatureUnit: string; compactTables: boolean; operationalAlerts: boolean; predictionAlerts: boolean; }
const defaults: PlatformSettings = { defaultRegion: "All Regions", refreshInterval: "15", emissionsFactor: "0.57", temperatureUnit: "celsius", compactTables: true, operationalAlerts: true, predictionAlerts: true };
const storageKey = "energy-digital-twin-settings";

export function SettingsPanel() {
  const [settings, setSettings] = useState<PlatformSettings>(() => { try { return { ...defaults, ...JSON.parse(localStorage.getItem(storageKey) ?? "{}") }; } catch { return defaults; } });
  const [saved, setSaved] = useState(false);
  useEffect(() => { if (!saved) return; const timer = window.setTimeout(() => setSaved(false), 2500); return () => window.clearTimeout(timer); }, [saved]);
  const set = <K extends keyof PlatformSettings>(key: K, value: PlatformSettings[K]) => setSettings((current) => ({ ...current, [key]: value }));
  const save = () => { localStorage.setItem(storageKey, JSON.stringify(settings)); setSaved(true); };
  const reset = () => { setSettings(defaults); localStorage.removeItem(storageKey); setSaved(true); };
  return <div className="mx-auto max-w-5xl space-y-5"><div className="rounded-2xl bg-gradient-to-r from-purple-950 to-purple-800 p-6 text-white"><div className="flex items-center gap-3"><div className="rounded-xl bg-white/10 p-3"><Palette size={22}/></div><div><h2 className="text-2xl font-black">Platform Settings</h2><p className="mt-1 text-sm text-purple-200">Configure the default engineering view and local user preferences.</p></div></div></div>{saved && <div className="flex items-center gap-2 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-800"><ShieldCheck size={17}/> Settings saved successfully.</div>}
    <SettingsSection icon={<Globe2 size={18}/>} title="General preferences" description="Set the default portfolio scope and measurement display."><Field label="Default region"><select value={settings.defaultRegion} onChange={(event) => set("defaultRegion", event.target.value)} className="setting-input"><option>All Regions</option><option>Central</option><option>East</option><option>West</option><option>South</option></select></Field><Field label="Temperature unit"><select value={settings.temperatureUnit} onChange={(event) => set("temperatureUnit", event.target.value)} className="setting-input"><option value="celsius">Celsius (°C)</option><option value="fahrenheit">Fahrenheit (°F)</option></select></Field><Toggle label="Compact site tables" note="Display more portfolio rows on screen." checked={settings.compactTables} onChange={(value) => set("compactTables", value)}/></SettingsSection>
    <SettingsSection icon={<Database size={18}/>} title="Model configuration" description="Define browser-level defaults for calculations and refresh behaviour."><Field label="Refresh interval"><select value={settings.refreshInterval} onChange={(event) => set("refreshInterval", event.target.value)} className="setting-input"><option value="5">Every 5 minutes</option><option value="15">Every 15 minutes</option><option value="30">Every 30 minutes</option><option value="60">Every hour</option></select></Field><Field label="Grid emissions factor (kg CO₂/kWh)"><input value={settings.emissionsFactor} onChange={(event) => set("emissionsFactor", event.target.value)} inputMode="decimal" className="setting-input"/></Field><div className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-xs leading-5 text-amber-900 md:col-span-2">These preferences affect the local display only. Production model coefficients should be managed in future Supabase configuration tables with controlled access and an audit trail.</div></SettingsSection>
    <SettingsSection icon={<Bell size={18}/>} title="Notifications" description="Choose which future platform events should generate alerts."><Toggle label="Operational alerts" note="Power-source, cooling and autonomy threshold events." checked={settings.operationalAlerts} onChange={(value) => set("operationalAlerts", value)}/><Toggle label="Prediction alerts" note="Sites forecast to cross a risk threshold." checked={settings.predictionAlerts} onChange={(value) => set("predictionAlerts", value)}/></SettingsSection>
    <div className="flex flex-wrap justify-end gap-3"><button onClick={reset} className="inline-flex items-center gap-2 rounded-xl border border-border bg-card px-5 py-2.5 text-sm font-bold text-muted-foreground hover:text-foreground"><RotateCcw size={15}/> Restore defaults</button><button onClick={save} className="inline-flex items-center gap-2 rounded-xl bg-purple-800 px-6 py-2.5 text-sm font-black text-white shadow hover:bg-purple-700"><Save size={15}/> Save settings</button></div></div>;
}
function SettingsSection({ icon, title, description, children }: { icon: ReactNode; title: string; description: string; children: ReactNode }) { return <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="mb-5 flex items-start gap-3"><div className="rounded-lg bg-purple-100 p-2 text-purple-800">{icon}</div><div><h3 className="font-black text-foreground">{title}</h3><p className="mt-0.5 text-xs text-muted-foreground">{description}</p></div></div><div className="grid gap-4 md:grid-cols-2">{children}</div></section>; }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="space-y-1.5 text-xs font-bold text-foreground"><span>{label}</span>{children}</label>; }
function Toggle({ label, note, checked, onChange }: { label: string; note: string; checked: boolean; onChange: (value: boolean) => void }) { return <div className="flex items-center justify-between gap-4 rounded-xl border border-border p-4"><span><span className="block text-xs font-black text-foreground">{label}</span><span className="mt-1 block text-[11px] text-muted-foreground">{note}</span></span><button type="button" role="switch" aria-checked={checked} onClick={() => onChange(!checked)} className={`relative h-6 w-11 shrink-0 rounded-full transition ${checked ? "bg-purple-700" : "bg-gray-300"}`}><span className={`absolute top-1 h-4 w-4 rounded-full bg-white transition ${checked ? "left-6" : "left-1"}`}/></button></div>; }
