import type { ReactNode } from "react";
import { Activity, ArrowRight, BarChart3, CheckCircle2, Database, FlaskConical, Leaf, Map, Radio, Settings, ShieldCheck, Zap } from "lucide-react";
import type { SiteAnalysis } from "../lib/calculations";

type Destination = "overview" | "twin" | "scenarios" | "map" | "sites" | "methodology" | "settings";

interface WebsiteHomeProps { analyses: SiteAnalysis[]; onNavigate: (destination: Destination) => void; }

export function WebsiteHome({ analyses, onNavigate }: WebsiteHomeProps) {
  const atRisk = analyses.filter((item) => item.overallRisk === "risk").length;
  const healthy = analyses.length - atRisk;
  const totalLoad = analyses.reduce((sum, item) => sum + item.site.telecomPowerKw, 0);
  const modules: Array<{ title: string; description: string; destination: Destination; icon: ReactNode; accent: string }> = [
    { title: "Digital Twin Workspace", description: "Simulate site energy balance, cooling headroom and battery autonomy under changing conditions.", destination: "twin", icon: <Activity size={20}/>, accent: "from-purple-600 to-indigo-700" },
    { title: "Scenario Laboratory", description: "Apply the four approved operational scenarios and identify exposed COW sites.", destination: "scenarios", icon: <FlaskConical size={20}/>, accent: "from-fuchsia-600 to-purple-700" },
    { title: "Geospatial Risk", description: "Explore portfolio health and predicted constraints across the Kingdom.", destination: "map", icon: <Map size={20}/>, accent: "from-cyan-600 to-blue-700" },
    { title: "Site Portfolio", description: "Search, compare and inspect the engineering profile of every validated site.", destination: "sites", icon: <Radio size={20}/>, accent: "from-emerald-600 to-teal-700" },
  ];
  return <div className="mx-auto max-w-[1500px] space-y-5">
    <section className="relative overflow-hidden rounded-3xl bg-gradient-to-br from-[#16072e] via-[#32105f] to-[#5c1688] p-6 text-white shadow-xl sm:p-9">
      <div className="absolute -right-16 -top-20 h-64 w-64 rounded-full bg-fuchsia-400/20 blur-3xl"/><div className="absolute bottom-0 right-[22%] h-36 w-36 rounded-full bg-cyan-300/10 blur-3xl"/>
      <div className="relative max-w-4xl"><div className="mb-4 inline-flex items-center gap-2 rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-[11px] font-bold uppercase tracking-[0.18em] text-purple-100"><ShieldCheck size={14}/> Predictive operations platform</div><h2 className="max-w-3xl text-3xl font-black leading-tight sm:text-4xl">Energy intelligence for every COW site.</h2><p className="mt-3 max-w-3xl text-sm leading-6 text-purple-100 sm:text-base">A single engineering website for portfolio monitoring, environmental forecasting, scenario simulation and site-level intervention planning.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={() => onNavigate("twin")} className="inline-flex items-center gap-2 rounded-xl bg-white px-5 py-3 text-sm font-black text-purple-900 shadow-lg transition hover:-translate-y-0.5">Launch Digital Twin <ArrowRight size={16}/></button><button onClick={() => onNavigate("overview")} className="inline-flex items-center gap-2 rounded-xl border border-white/25 bg-white/10 px-5 py-3 text-sm font-bold text-white transition hover:bg-white/20">View portfolio analytics <BarChart3 size={16}/></button></div></div>
    </section>
    <section className="grid grid-cols-2 gap-3 lg:grid-cols-4"><HomeMetric label="Validated sites" value={analyses.length.toString()} note="Current model dataset" icon={<Database size={18}/>} tone="purple"/><HomeMetric label="Healthy sites" value={healthy.toString()} note="Within operating margins" icon={<CheckCircle2 size={18}/>} tone="green"/><HomeMetric label="Attention required" value={atRisk.toString()} note="Predictive constraints detected" icon={<ShieldCheck size={18}/>} tone="orange"/><HomeMetric label="Connected load" value={`${totalLoad.toFixed(0)} kW`} note="Portfolio telecom demand" icon={<Zap size={18}/>} tone="blue"/></section>
    <section><div className="mb-3 flex items-end justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-purple-700">Platform modules</p><h3 className="mt-1 text-xl font-black text-foreground">Choose a workspace</h3></div><button onClick={() => onNavigate("settings")} className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-xs font-bold text-muted-foreground hover:text-foreground"><Settings size={14}/> Platform settings</button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{modules.map((module) => <button key={module.title} onClick={() => onNavigate(module.destination)} className="group overflow-hidden rounded-2xl border border-border bg-card text-left shadow-sm transition hover:-translate-y-1 hover:shadow-lg"><div className={`h-1.5 bg-gradient-to-r ${module.accent}`}/><div className="p-5"><div className={`mb-4 inline-flex rounded-xl bg-gradient-to-br p-3 text-white shadow ${module.accent}`}>{module.icon}</div><h4 className="font-black text-foreground">{module.title}</h4><p className="mt-2 min-h-[60px] text-sm leading-5 text-muted-foreground">{module.description}</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-black text-purple-700">Open module <ArrowRight size={13} className="transition group-hover:translate-x-1"/></span></div></button>)}</div></section>
    <section className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-5 shadow-sm lg:col-span-2"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[0.16em] text-purple-700">Operating model</p><h3 className="mt-1 text-lg font-black">From data to preventive action</h3></div><Leaf className="text-emerald-600"/></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><ProcessStep number="01" title="Observe" body="Asset, weather and operational inputs establish the site baseline."/><ProcessStep number="02" title="Predict" body="Engineering models forecast energy, cooling and autonomy margins."/><ProcessStep number="03" title="Act" body="Teams prioritize the highest-impact site interventions before outage."/></div></div><div className="rounded-2xl border border-purple-200 bg-gradient-to-br from-purple-50 to-white p-5 shadow-sm"><div className="flex items-center gap-2 text-purple-800"><Activity size={18}/><h3 className="font-black">Platform status</h3></div><div className="mt-4 space-y-3"><StatusRow label="Model engine" value="Online"/><StatusRow label="Scenario library" value="S1–S4 active"/><StatusRow label="Dataset" value={`${analyses.length} sites`}/><StatusRow label="Live telemetry" value="Ready to connect" muted/></div><button onClick={() => onNavigate("methodology")} className="mt-5 inline-flex items-center gap-1 text-xs font-black text-purple-800">View model and data contract <ArrowRight size={13}/></button></div></section>
  </div>;
}

function HomeMetric({ label, value, note, icon, tone }: { label: string; value: string; note: string; icon: ReactNode; tone: "purple" | "green" | "orange" | "blue" }) { const colors = { purple: "bg-purple-100 text-purple-800", green: "bg-emerald-100 text-emerald-800", orange: "bg-orange-100 text-orange-800", blue: "bg-blue-100 text-blue-800" }; return <div className="rounded-2xl border border-border bg-card p-4 shadow-sm sm:p-5"><div className={`inline-flex rounded-lg p-2 ${colors[tone]}`}>{icon}</div><div className="mt-3 text-2xl font-black text-foreground">{value}</div><div className="text-xs font-bold text-foreground">{label}</div><div className="mt-1 text-[11px] text-muted-foreground">{note}</div></div>; }
function ProcessStep({ number, title, body }: { number: string; title: string; body: string }) { return <div className="rounded-xl bg-muted/50 p-4"><span className="text-xs font-black text-purple-700">{number}</span><h4 className="mt-1 font-black">{title}</h4><p className="mt-1 text-xs leading-5 text-muted-foreground">{body}</p></div>; }
function StatusRow({ label, value, muted = false }: { label: string; value: string; muted?: boolean }) { return <div className="flex items-center justify-between gap-3 border-b border-purple-100 pb-2 text-xs"><span className="text-muted-foreground">{label}</span><span className={`font-black ${muted ? "text-amber-700" : "text-emerald-700"}`}>{value}</span></div>; }
