const colors = {
  light: {
    text:               "#0a0a0a",
    tint:               "#6B21C8",
    background:         "#0D0A1A",
    foreground:         "#FFFFFF",
    card:               "#1A1135",
    cardForeground:     "#FFFFFF",
    primary:            "#6B21C8",
    primaryForeground:  "#FFFFFF",
    secondary:          "#2A1E4A",
    secondaryForeground:"#D4C8F0",
    muted:              "#1E1540",
    mutedForeground:    "#8B7DAE",
    accent:             "#9333EA",
    accentForeground:   "#FFFFFF",
    destructive:        "#E8175D",
    destructiveForeground: "#FFFFFF",
    border:             "#2D1F50",
    input:              "#231A45",
    safe:               "#00BFB3",
    onDuty:             "#00BFB3",
    offDuty:            "#4A3A6E",
  },
  dark: {
    text:               "#0a0a0a",
    tint:               "#6B21C8",
    background:         "#0D0A1A",
    foreground:         "#FFFFFF",
    card:               "#1A1135",
    cardForeground:     "#FFFFFF",
    primary:            "#6B21C8",
    primaryForeground:  "#FFFFFF",
    secondary:          "#2A1E4A",
    secondaryForeground:"#D4C8F0",
    muted:              "#1E1540",
    mutedForeground:    "#8B7DAE",
    accent:             "#9333EA",
    accentForeground:   "#FFFFFF",
    destructive:        "#E8175D",
    destructiveForeground: "#FFFFFF",
    border:             "#2D1F50",
    input:              "#231A45",
    safe:               "#00BFB3",
    onDuty:             "#00BFB3",
    offDuty:            "#4A3A6E",
  },
  radius: 12,
};

export default colors;
